apiVersion: batch/v1
kind: Job
metadata:
  name: {{name}}
spec:
  template:
    spec:
      containers:
      {{#each containers}}
      - name: {{name}}
        image: {{image}}
        command: {{{json command}}}
        {{#if ../env}}
        env:
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        {{#each ../env}}
        - name: {{name}}
          value: "{{value}}"
        {{/each}}
        {{/if}}
        volumeMounts:
        - name: ucdlib-service-init
          mountPath: /etc/ucdlib-service-init
          readOnly: true
        - mountPath: /etc/google
          name: service-account
        {{#each ../volumes}}
        - name: {{name}}
          mountPath: {{mountPath}}
        {{/each}}
      {{/each}}
      restartPolicy: Never
      volumes:
      - name: service-account
        secret:
          secretName: service-account
      {{#each volumes}}
      - name: {{name}}
        hostPath:
          path: /hosthome/{{../HOME_HOST_PATH}}/{{hostPath}}
          {{#if type}}
          type: {{type}}
          {{/if}}
      {{/each}}
      - name: ucdlib-service-init
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/services/init
  backoffLimit: 3