apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{pvc-name}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: {{pv-name}}
  resources:
    requests:
      storage: {{pv-size}}