version: '3'
services:

  zookeeper:
    image: :
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: :
    env_file:
      - .env
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  redis:
    image: :
    volumes:
      - redis-data:/data

  composer:
    image: localhost/local-dev/casita-a6t-controller:v0.0.1-alpha
    env_file:
      - .env
    command: node composer/instance.js

  expire:
    image: localhost/local-dev/casita-a6t-controller:v0.0.1-alpha
    env_file:
      - .env
    command: node expire/instance.js

  init:
    image: localhost/local-dev/casita-a6t-controller:v0.0.1-alpha
    env_file:
      - .env
    command: node init

  decoder:
    image: :v0.0.1-alpha
    env_file:
      - .env
    volumes:
      - ./ssh.key:/root/.ssh/id_rsa
    environment:
      - GRB_FILE=decoded
    restart: always

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog:
  redis-data: