apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
spec:
  selector:
    matchLabels:
      app:  {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app:  {{SERVICE_NAME}}
    spec:
      containers:
      - name: {{SERVICE_NAME}}
        image: {{CASITA_IMAGE_NAME_TAG}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {{#if COMMAND}}
        command: ["{{{COMMAND}}}"]
        {{/if}}
        {{#if ARGS}}
        args: {{{json ARGS}}}
        {{/if}}
        env:
        - name: K8S_ENV
          value: "{{K8S_ENV}}"
        - name: K8S_LOG_LEVEL
          value: "{{K8S_LOG_LEVEL}}"
        {{#each env}}
        - name: {{name}}
          value: "{{value}}"
        {{/each}}
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /storage/nfs
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: {{FILESTORE_VOLUME_NAME}}-claim
          readOnly: false
      - name: service-account
        secret:
          secretName: service-account
      {{#if nodeSelector}}
      nodeSelector:
        {{#if intendedfor}}
        intendedfor: {{intendedfor}}
        {{/if}}
      {{/if}}