apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
spec:
  {{#if replicas}}
  replicas: {{replicas}}
  {{/if}}
  selector:
    matchLabels:
      app:  {{SERVICE_NAME}}
  template:
    metadata:
      labels:
        app:  {{SERVICE_NAME}}
    spec:
      containers:
      - name: {{SERVICE_NAME}}
        image: {{CASITA_IMAGE_NAME_TAG}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {{#if COMMAND}}
        command: ["{{{COMMAND}}}"]
        {{/if}}
        {{#if ARGS}}
        args: {{{json ARGS}}}
        {{/if}}
        env:
        - name: INSTANCE_ENV
          value: "{{K8S_ENV}}"
        - name: LOG_LEVEL
          value: "{{K8S_LOG_LEVEL}}"
        - name : "GOOGLE_APPLICATION_CREDENTIALS"
          value : "/etc/google/service-account.json"
        {{#each env}}
        - name: {{name}}
          value: "{{value}}"
        {{/each}}
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "{{K8S_DEPLOYMENT_CPU}}"
        volumeMounts:
        - mountPath: /storage/network
          name: nfspsc
        - mountPath: /etc/google
          name: service-account
      volumes:
      - name: nfspsc
        persistentVolumeClaim:
          claimName: {{FILESTORE_VOLUME_NAME}}-claim
          readOnly: false
      - name: service-account
        secret:
          secretName: service-account
      {{#if nodeSelector}}
      nodeSelector:
        {{#if nodeSelector.intendedfor}}
        intendedfor: {{nodeSelector.intendedfor}}
        {{/if}}
      {{/if}}