apiVersion: v1
kind: Service
metadata:
  name: {{serviceName}}-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{API_SERVICE_INTERNAL_IP}}"
  selector:
    app: {{serviceName}}
  ports:
  - protocol: TCP
    port: {{port}}
    targetPort: {{port}}